version: 2.1

orbs:
  helm: banzaicloud/helm@0.0.7

executors:
  helm2:
    docker:
      - image: banzaicloud/helm:0.0.4

helm-repositories: &helm_repositories
  - run: helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
  - run: helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
  - run: helm repo add rimusz https://charts.rimusz.net

workflows:
  version: 2
  static-checks:
    jobs:
      - helm/lint-chart:
          name: Lint (Helm 2)
          executor: helm2
          charts-dir: '.'
          add-extra-repositories: *helm_repositories
          filters:
            tags:
              ignore: /.*/
  helm-3-lint:
    jobs:
      - helm/lint-chart:
          name: Lint (Helm 3)
          executor: helm/helm3
          charts-dir: '.'
          add-extra-repositories: *helm_repositories
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - helm/publish-chart:
          context: helm
          charts-dir: '.'
          add-extra-repositories: *helm_repositories
          filters:
            tags:
              only: /\S+\/\d+.\d+.\d+(?:-(?:dev|rc|banzai)\.\d+)?/
            branches:
              ignore: /.*/
